# Generated by scbake
# This Makefile is aware of your project structure.

.PHONY: all build clean

all: build

build:
{{- range .Projects }}
	@echo "Building {{.Name}}..."
	(cd {{.Path}} && go build -v .)
{{- end }}

clean:
	@echo "Cleaning..."
{{- range .Projects }}
	(cd {{.Path}} && go clean)
{{- end }}