# Generated by scbake

.PHONY: all build clean help lint lint-fix

all: build

# --- Standard Targets ---

help:
	@echo "Available commands (Targets dynamically generated from scbake.toml):"
	@echo "------------------------------------------------------------------"
	@echo "  build         : Builds all tracked projects."
	@echo "  clean         : Cleans all tracked projects."
	@echo "  lint          : Runs linting/formatting on all tracked projects."
	@echo "  lint-fix      : Runs linting/formatting with auto-fix on all tracked projects."
	@echo "  help          : Show this help message."
	@echo "------------------------------------------------------------------"
	
# --- Main Build Target ---
build:
{{- range .Projects }}
	@echo "Building {{.Name}} ({{.Language}})..."
	(cd {{.Path}} && $(MAKE_BUILD_COMMAND_{{.Language}}))
{{- end }}

# --- Main Clean Target ---
clean:
	@echo "Cleaning projects..."
{{- range .Projects }}
	@echo "Cleaning {{.Name}}..."
	(cd {{.Path}} && $(MAKE_CLEAN_COMMAND_{{.Language}}))
{{- end }}

# --- Main Lint Targets ---

lint:
	@echo "Running lint checks..."
{{- range .Projects }}
	@echo "Linting {{.Name}}..."
	(cd {{.Path}} && $(MAKE_LINT_COMMAND_{{.Language}}))
{{- end }}

lint-fix:
	@echo "Running lint fixes..."
{{- range .Projects }}
	@echo "Fixing {{.Name}}..."
	(cd {{.Path}} && $(MAKE_LINT_FIX_COMMAND_{{.Language}}))
{{- end }}

# -----------------------------------------------------------
#  Language Specific Command Definitions (Internal Use)
# -----------------------------------------------------------

# Go Commands (Uses golangci-lint config assumed to be present)
# FIX: Corrected LINT and LINT_FIX commands to use 'run' and include './...'
MAKE_BUILD_COMMAND_go := go build -v .
MAKE_CLEAN_COMMAND_go := go clean
MAKE_LINT_COMMAND_go := golangci-lint run ./...
MAKE_LINT_FIX_COMMAND_go := golangci-lint run --fix --timeout=5m ./...

# Svelte/Node Commands (Uses ESLint/Prettier setup assumed to be present)
MAKE_BUILD_COMMAND_svelte := npm run build
MAKE_CLEAN_COMMAND_svelte := rm -rf dist node_modules
MAKE_LINT_COMMAND_svelte := npm run lint
MAKE_LINT_FIX_COMMAND_svelte := npm run lint -- --fix

# Spring/Java Commands (Uses Maven Checkstyle plugin, assumed to be present)
MAKE_BUILD_COMMAND_spring := ./mvnw clean package -DskipTests
MAKE_CLEAN_COMMAND_spring := ./mvnw clean
MAKE_LINT_COMMAND_spring := ./mvnw checkstyle:check
MAKE_LINT_FIX_COMMAND_spring := echo "Fix command not applicable for Maven Checkstyle"